version: '2'

services:
    opentsdb:
        container_name: opentsdb
        image: petergrace/opentsdb-docker:latest
        ports:
            - 4242:4242
            - 60030:60030
        volumes:
             - hbase_data:/data/hbase
             - tsdb_tmp:/tmp
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        links:
            - opentsdb
        volumes:
            - grafana_etc:/etc/grafana
            - grafana_lib:/var/lib/grafana
            - grafana_plugins:/var/lib/grafana/plugins
            - grafana_log:/var/log/grafana

    add_grafana_datasource:
        build:
            context: .
            dockerfile: Dockerfile.add_grafana_datasource
        environment:
            GRAFANA_HOST: grafana
            TSDB_HOST: opentsdb
        links:
            - grafana

volumes:
    grafana_etc:
    grafana_lib:
    grafana_plugins:
    grafana_log:
    hbase_data:
    tsdb_tmp:
